workflows:
  android-tv:
    name: DaepTV_Masjid Build
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: 11
    scripts:
      - name: Set up JDK
        script: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - name: Build APK
        script: |
          chmod +x gradlew
          ./gradlew clean assembleRelease --stacktrace
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - utthafandhy@gmail.com
